// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by flutter_native_bridge
// Run: dart run flutter_native_bridge:generate

import 'package:flutter/services.dart';

const _channel = MethodChannel('flutter_native_bridge');
const _eventChannelPrefix = 'flutter_native_bridge/events/';

/// Generated bridge for DeviceService
class DeviceService {
  DeviceService._();

  /// Calls native DeviceService.getDeviceModel
  static Future<String?> getDeviceModel() async {
    return _channel.invokeMethod<String>('DeviceService.getDeviceModel');
  }

  /// Calls native DeviceService.getAndroidVersion
  static Future<int?> getAndroidVersion() async {
    return _channel.invokeMethod<int>('DeviceService.getAndroidVersion');
  }

  /// Calls native DeviceService.getManufacturer
  static Future<String?> getManufacturer() async {
    return _channel.invokeMethod<String>('DeviceService.getManufacturer');
  }

  /// Calls native DeviceService.getIOSVersion
  static Future<String?> getIOSVersion() async {
    return _channel.invokeMethod<String>('DeviceService.getIOSVersion');
  }

  /// Calls native DeviceService.getDeviceName
  static Future<String?> getDeviceName() async {
    return _channel.invokeMethod<String>('DeviceService.getDeviceName');
  }

  /// Calls native DeviceService.greetWithName
  static Future<String?> greetWithName(String name) async {
    return _channel.invokeMethod<String>('DeviceService.greetWithName', name);
  }
}

/// Generated bridge for BatteryService
class BatteryService {
  BatteryService._();

  /// Calls native BatteryService.getBatteryLevel
  static Future<int?> getBatteryLevel() async {
    return _channel.invokeMethod<int>('BatteryService.getBatteryLevel');
  }

  /// Calls native BatteryService.isCharging
  static Future<bool?> isCharging() async {
    return _channel.invokeMethod<bool>('BatteryService.isCharging');
  }

  /// Calls native BatteryService.getBatteryState
  static Future<String?> getBatteryState() async {
    return _channel.invokeMethod<String>('BatteryService.getBatteryState');
  }
}

/// Generated bridge for CounterService
class CounterService {
  CounterService._();

  /// Calls native CounterService.stopCounter
  static Future<void> stopCounter() async {
    return _channel.invokeMethod<void>('CounterService.stopCounter');
  }

  /// Subscribes to native CounterService.counterUpdates stream
  static Stream<dynamic> counterUpdates() {
    const channelName = '${_eventChannelPrefix}CounterService.counterUpdates';
    const eventChannel = EventChannel(channelName);
    return eventChannel.receiveBroadcastStream().cast<dynamic>();
  }
}

/// Generated bridge for MainActivity
class MainActivity {
  MainActivity._();

  /// Calls native MainActivity.greet
  static Future<String?> greet(String name) async {
    return _channel.invokeMethod<String>('MainActivity.greet', name);
  }

  /// Calls native MainActivity.getData
  static Future<Map<String, dynamic>?> getData(Map<String, dynamic> data) async {
    return _channel.invokeMethod<Map<String, dynamic>>('MainActivity.getData', data);
  }
}

