// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by flutter_native_bridge
// Run: dart run flutter_native_bridge:generate

import 'package:flutter/services.dart';

const _channel = MethodChannel('flutter_native_bridge');

/// Generated bridge for DeviceService
class DeviceService {
  DeviceService._();

  /// Calls native DeviceService.getDeviceModel
  static Future<String?> getDeviceModel() async {
    return _channel.invokeMethod<String>('DeviceService.getDeviceModel');
  }

  /// Calls native DeviceService.getAndroidVersion
  static Future<int?> getAndroidVersion() async {
    return _channel.invokeMethod<int>('DeviceService.getAndroidVersion');
  }

  /// Calls native DeviceService.getManufacturer
  static Future<String?> getManufacturer() async {
    return _channel.invokeMethod<String>('DeviceService.getManufacturer');
  }

  /// Calls native DeviceService.getBatteryLevel
  static Future<int?> getBatteryLevel() async {
    return _channel.invokeMethod<int>('DeviceService.getBatteryLevel');
  }

  /// Calls native DeviceService.isCharging
  static Future<bool?> isCharging() async {
    return _channel.invokeMethod<bool>('DeviceService.isCharging');
  }
}

/// Generated bridge for BatteryService
class BatteryService {
  BatteryService._();

  /// Calls native BatteryService.getBatteryLevel
  static Future<int?> getBatteryLevel() async {
    return _channel.invokeMethod<int>('BatteryService.getBatteryLevel');
  }

  /// Calls native BatteryService.isCharging
  static Future<bool?> isCharging() async {
    return _channel.invokeMethod<bool>('BatteryService.isCharging');
  }
}

/// Generated bridge for MainActivity
class MainActivity {
  MainActivity._();

  /// Calls native MainActivity.greet
  static Future<String?> greet(String name) async {
    return _channel.invokeMethod<String>('MainActivity.greet', name);
  }

  /// Calls native MainActivity.getData
  static Future<Map<dynamic, dynamic>?> getData(Map<dynamic, dynamic> data) async {
    return _channel.invokeMethod<Map<dynamic, dynamic>>('MainActivity.getData', data);
  }
}

